# Configuration for the Kosher Chain Node

[api]
listen_address = "127.0.0.1:3000"

[p2p]
listen_address = "/ip4/0.0.0.0/tcp/0"

[witness]
xrpl_node_url = "wss://s1.ripple.com:51234"
door_account = "rReceivingAccountOnXrpl..."
confirmation_threshold = 10

[chain]
validators_file = "validators.json"

# --- Optional Validator Configuration ---
# If this section is present, the node will attempt to run as a validator.
# [validator]
# key_file = "validator_key.json"
